name: Lighthouse Audit
on:
  pull_request:
    branches: [main]
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm install -g pnpm && pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Start Application
        run: pnpm run dev &
        env:
          PORT: 3000
      - name: Wait for Application to be Ready
        run: sleep 10
      - name: Run Lighthouse Audit
        run: pnpm run test:performance
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: lighthouse-report
          path: lighthouse-reports/
          retention-days: 30
